name: Nightly Build

on:
  schedule:
    # Запускается каждый день в 2:00 UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  nightly-build:
    runs-on: ubuntu-latest
    name: Nightly Build and Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build and test
        run: ./gradlew --no-daemon clean build

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: nightly-test-results
          path: build/reports/tests/
          retention-days: 7